[package]
name = "cae"
version = "0.0.1"
authors = ["zovt <zovt@posteo.de>"]
license = "GPL-3.0"

[dependencies]
glium = "0.20.0"
cgmath = "0.16.0"
clap = "2.29.0"
harfbuzz-sys = "0.1.15"
freetype = "0.3.0"

[build-dependencies]
bindgen = "0.32.3"
pkg-config = "0.3.9"